### ISSUE TITLE
This repo needs to be published

### ISSUE THREAD

**Issue by chick** [freechipsproject/ip-contributions#5]
We need to have this REPO published to maven.

**Comment by ucbjrl** [comment]
Should we have a top-level LICENSE file containing the unlicense? That way, GitHub will know that this repo is (un)licensed.

**Comment by chick** [comment]
That sounds like a good idea, but maybe we should formalize that at governance tomorrow.

**Comment by schoeberl** [comment]
I have published a local fork of ip-contribution at Maven (with my personal groupId), which is a workaround for my own usage.

```
libraryDependencies += "io.github.schoeberl" % "ip-contributions" % "1.0.0"
```

I can take responsibility for publishing this repo (along with new Chisel versions are published). For this, I guess, I should have write access to this repo and someone needs to add my Sonatype user (schoeberl) to the "edu.berkeley.cs" groupId.

Cheers,
Martin

**Comment by ekiwi** [comment]
Thanks for the initiative, Martin!

Before we officially publish this library, we should make sure to set the version to something reasonable.
Ideally we would do something like: `0.4.x`
The leading zero would allow us to make breaking changes without the need to go through a deprecation cycle. The `4` indicates the Chisel version that this library will be compiled with.

**Comment by schoeberl** [comment]
Ok, I can do. But this would be a regression from the 1.0.0 as it was originally set. Maybe this is OK.

Martin

**Comment by schoeberl** [comment]
done
